# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os: linux
cran: https://demo.rstudiopm.com/cran/__linux__/xenial/latest

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libsodium-dev

jobs:
  include:

  - stage: "Test"
    r: release
    r_build_args: --no-build-vignettes
    r_check_args: --ignore-vignettes --no-examples
    after_success:
    - Rscript -e 'covr::codecov()'

  - stage: "Test"
    name: "as CRAN"
    r: release
    env:
      GCALENDR_PASSWORD=''
      not_cran=false

  - stage: "Test"
    r: devel
    r_build_args: --no-build-vignettes
    r_check_args: --ignore-vignettes --no-examples

  - stage: "Test"
    r: oldrel
    r_build_args: --no-build-vignettes
    r_check_args: --ignore-vignettes --no-examples

