# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os: linux

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libsodium-dev

jobs:
  include:

    - stage: "Test"
      r: release
      after_success:
      - Rscript -e 'covr::codecov()'
      - find . -name testthat.Rout | xargs cat
      after_failure:
      - find . -name testthat.Rout | xargs cat

    - stage: "Test"
      r: devel
      env: GCALENDR_PASSWORD=''
      r_build_args: --no-build-vignettes
      r_check_args: --ignore-vignettes --no-examples

    - stage: "Test"
      r: release
      env: GCALENDR_PASSWORD=''
      r_build_args: --no-build-vignettes
      r_check_args: --ignore-vignettes --no-examples

    - stage: "Test"
      r: oldrel
      env: GCALENDR_PASSWORD=''
      r_build_args: --no-build-vignettes
      r_check_args: --ignore-vignettes --no-examples

    - stage: "Deploy"
      r: release
      name: "Deploy gh-pages"
      if: branch IN (master, travis) AND repo = andrie/gcalendr AND type = push
      before_cache:
      - Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'


