# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: r
cache: packages
os: linux
cran: https://demo.rstudiopm.com/cran/__linux__/xenial/latest

addons:
  apt:
    sources:
    - sourceline: 'ppa:chris-lea/libsodium'
    packages:
    - libsodium-dev

jobs:
  include:

  - stage: "Test"
    r: release
    r_build_args: --no-build-vignettes
    r_check_args: --ignore-vignettes --no-examples
    after_success:
    - Rscript -e 'covr::codecov()'
    - find . -name testthat.Rout | xargs cat
    after_failure:
    - find . -name testthat.Rout | xargs cat
    before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
    deploy:
      provider: script
      script: Rscript -e 'pkgdown::deploy_site_github(ssh_id = Sys.getenv("TRAVIS_DEPLOY_KEY", ""))'
      skip_cleanup: true

  - stage: "Test"
    name: "as CRAN"
    r: release
    env:
      GCALENDR_PASSWORD=''
      not_cran=false

  - stage: "Test"
    r: devel
    r_build_args: --no-build-vignettes
    r_check_args: --ignore-vignettes --no-examples

  - stage: "Test"
    r: oldrel
    r_build_args: --no-build-vignettes
    r_check_args: --ignore-vignettes --no-examples

